<?

namespace Consts;

/**
 * @author Abbas Ali Hashemian <info@namedin.com> http://namedin.com <tondarweb@gmail.com> http://webdesignir.com
 * @package Tondarweb Portal
 * @version 1
 * @copyright (c) Abbas Ali Hashemian
 * @access public
 */
class TimeZones {

	static $arrTimeZones = array(
		1 => array('NAME' => 'Pacific/Pago_Pago', 'OFFSET' => -39600, 'ABBREVIATION' => 'SST'),
		2 => array('NAME' => 'Pacific/Midway', 'OFFSET' => -39600, 'ABBREVIATION' => 'SST'),
		3 => array('NAME' => 'Pacific/Apia', 'OFFSET' => -39600, 'ABBREVIATION' => 'WST'),
		4 => array('NAME' => 'Pacific/Niue', 'OFFSET' => -39600, 'ABBREVIATION' => 'NUT'),
		5 => array('NAME' => 'Pacific/Tahiti', 'OFFSET' => -36000, 'ABBREVIATION' => 'TAHT'),
		6 => array('NAME' => 'Pacific/Johnston', 'OFFSET' => -36000, 'ABBREVIATION' => 'HST'),
		7 => array('NAME' => 'Pacific/Rarotonga', 'OFFSET' => -36000, 'ABBREVIATION' => 'CKT'),
		8 => array('NAME' => 'Pacific/Honolulu', 'OFFSET' => -36000, 'ABBREVIATION' => 'HST'),
		9 => array('NAME' => 'Pacific/Fakaofo', 'OFFSET' => -36000, 'ABBREVIATION' => 'TKT'),
		10 => array('NAME' => 'America/Adak', 'OFFSET' => -36000, 'ABBREVIATION' => 'HAST'),
		11 => array('NAME' => 'Pacific/Marquesas', 'OFFSET' => -34200, 'ABBREVIATION' => 'MART'),
		12 => array('NAME' => 'America/Yakutat', 'OFFSET' => -32400, 'ABBREVIATION' => 'AKST'),
		13 => array('NAME' => 'America/Nome', 'OFFSET' => -32400, 'ABBREVIATION' => 'AKST'),
		14 => array('NAME' => 'America/Anchorage', 'OFFSET' => -32400, 'ABBREVIATION' => 'AKST'),
		15 => array('NAME' => 'America/Juneau', 'OFFSET' => -32400, 'ABBREVIATION' => 'AKST'),
		16 => array('NAME' => 'Pacific/Gambier', 'OFFSET' => -32400, 'ABBREVIATION' => 'GAMT'),
		17 => array('NAME' => 'America/Los_Angeles', 'OFFSET' => -28800, 'ABBREVIATION' => 'PST'),
		18 => array('NAME' => 'America/Santa_Isabel', 'OFFSET' => -28800, 'ABBREVIATION' => 'PST'),
		19 => array('NAME' => 'America/Dawson', 'OFFSET' => -28800, 'ABBREVIATION' => 'PST'),
		20 => array('NAME' => 'America/Tijuana', 'OFFSET' => -28800, 'ABBREVIATION' => 'PST'),
		21 => array('NAME' => 'America/Vancouver', 'OFFSET' => -28800, 'ABBREVIATION' => 'PST'),
		22 => array('NAME' => 'Pacific/Pitcairn', 'OFFSET' => -28800, 'ABBREVIATION' => 'PST'),
		23 => array('NAME' => 'America/Whitehorse', 'OFFSET' => -28800, 'ABBREVIATION' => 'PST'),
		24 => array('NAME' => 'America/Phoenix', 'OFFSET' => -25200, 'ABBREVIATION' => 'MST'),
		25 => array('NAME' => 'America/Edmonton', 'OFFSET' => -25200, 'ABBREVIATION' => 'MST'),
		26 => array('NAME' => 'America/Hermosillo', 'OFFSET' => -25200, 'ABBREVIATION' => 'MST'),
		27 => array('NAME' => 'America/Inuvik', 'OFFSET' => -25200, 'ABBREVIATION' => 'MST'),
		28 => array('NAME' => 'America/Ojinaga', 'OFFSET' => -25200, 'ABBREVIATION' => 'MST'),
		29 => array('NAME' => 'America/Cambridge_Bay', 'OFFSET' => -25200, 'ABBREVIATION' => 'MST'),
		30 => array('NAME' => 'America/Dawson_Creek', 'OFFSET' => -25200, 'ABBREVIATION' => 'MST'),
		31 => array('NAME' => 'America/Mazatlan', 'OFFSET' => -25200, 'ABBREVIATION' => 'MST'),
		32 => array('NAME' => 'America/Yellowknife', 'OFFSET' => -25200, 'ABBREVIATION' => 'MST'),
		33 => array('NAME' => 'America/Chihuahua', 'OFFSET' => -25200, 'ABBREVIATION' => 'MST'),
		34 => array('NAME' => 'America/Shiprock', 'OFFSET' => -25200, 'ABBREVIATION' => 'MST'),
		35 => array('NAME' => 'America/Boise', 'OFFSET' => -25200, 'ABBREVIATION' => 'MST'),
		36 => array('NAME' => 'America/Denver', 'OFFSET' => -25200, 'ABBREVIATION' => 'MST'),
		37 => array('NAME' => 'America/Costa_Rica', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		38 => array('NAME' => 'America/El_Salvador', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		39 => array('NAME' => 'America/Managua', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		40 => array('NAME' => 'America/Matamoros', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		41 => array('NAME' => 'America/Cancun', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		42 => array('NAME' => 'America/Indiana/Knox', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		43 => array('NAME' => 'America/Belize', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		44 => array('NAME' => 'America/Indiana/Tell_City', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		45 => array('NAME' => 'America/Bahia_Banderas', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		46 => array('NAME' => 'America/Guatemala', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		47 => array('NAME' => 'America/Monterrey', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		48 => array('NAME' => 'America/Regina', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		49 => array('NAME' => 'America/Rankin_Inlet', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		50 => array('NAME' => 'America/Rainy_River', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		51 => array('NAME' => 'America/North_Dakota/New_Salem', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		52 => array('NAME' => 'America/Swift_Current', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		53 => array('NAME' => 'America/Tegucigalpa', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		54 => array('NAME' => 'Pacific/Easter', 'OFFSET' => -21600, 'ABBREVIATION' => 'EASST'),
		55 => array('NAME' => 'Pacific/Galapagos', 'OFFSET' => -21600, 'ABBREVIATION' => 'GALT'),
		56 => array('NAME' => 'America/Winnipeg', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		57 => array('NAME' => 'America/Menominee', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		58 => array('NAME' => 'America/North_Dakota/Center', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		59 => array('NAME' => 'America/Mexico_City', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		60 => array('NAME' => 'America/Chicago', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		61 => array('NAME' => 'America/Merida', 'OFFSET' => -21600, 'ABBREVIATION' => 'CST'),
		62 => array('NAME' => 'America/Detroit', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		63 => array('NAME' => 'America/Kentucky/Monticello', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		64 => array('NAME' => 'America/Kentucky/Louisville', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		65 => array('NAME' => 'America/Nassau', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		66 => array('NAME' => 'America/Resolute', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		67 => array('NAME' => 'America/Montreal', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		68 => array('NAME' => 'America/Lima', 'OFFSET' => -18000, 'ABBREVIATION' => 'PET'),
		69 => array('NAME' => 'America/Toronto', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		70 => array('NAME' => 'America/Thunder_Bay', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		71 => array('NAME' => 'America/Pangnirtung', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		72 => array('NAME' => 'America/Grand_Turk', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		73 => array('NAME' => 'America/Nipigon', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		74 => array('NAME' => 'America/Indiana/Petersburg', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		75 => array('NAME' => 'America/Indiana/Vevay', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		76 => array('NAME' => 'America/Indiana/Vincennes', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		77 => array('NAME' => 'America/Indiana/Winamac', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		78 => array('NAME' => 'America/Indiana/Marengo', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		79 => array('NAME' => 'America/Iqaluit', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		80 => array('NAME' => 'America/Guayaquil', 'OFFSET' => -18000, 'ABBREVIATION' => 'ECT'),
		81 => array('NAME' => 'America/Panama', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		82 => array('NAME' => 'America/Havana', 'OFFSET' => -18000, 'ABBREVIATION' => 'CST'),
		83 => array('NAME' => 'America/Jamaica', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		84 => array('NAME' => 'America/Indiana/Indianapolis', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		85 => array('NAME' => 'America/New_York', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		86 => array('NAME' => 'America/Port-au-Prince', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		87 => array('NAME' => 'America/Bogota', 'OFFSET' => -18000, 'ABBREVIATION' => 'COT'),
		88 => array('NAME' => 'America/Cayman', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		89 => array('NAME' => 'America/Atikokan', 'OFFSET' => -18000, 'ABBREVIATION' => 'EST'),
		90 => array('NAME' => 'America/Caracas', 'OFFSET' => -16200, 'ABBREVIATION' => 'VET'),
		91 => array('NAME' => 'America/Puerto_Rico', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		92 => array('NAME' => 'America/Porto_Velho', 'OFFSET' => -14400, 'ABBREVIATION' => 'AMT'),
		93 => array('NAME' => 'America/Thule', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		94 => array('NAME' => 'America/St_Vincent', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		95 => array('NAME' => 'America/Port_of_Spain', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		96 => array('NAME' => 'America/St_Thomas', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		97 => array('NAME' => 'America/St_Lucia', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		98 => array('NAME' => 'America/Tortola', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		99 => array('NAME' => 'Atlantic/Stanley', 'OFFSET' => -14400, 'ABBREVIATION' => 'FKST'),
		100 => array('NAME' => 'America/Argentina/San_Luis', 'OFFSET' => -14400, 'ABBREVIATION' => 'WARST'),
		101 => array('NAME' => 'America/Anguilla', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		102 => array('NAME' => 'America/Marigot', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		103 => array('NAME' => 'America/Martinique', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		104 => array('NAME' => 'America/Moncton', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		105 => array('NAME' => 'Antarctica/Palmer', 'OFFSET' => -14400, 'ABBREVIATION' => 'CLST'),
		106 => array('NAME' => 'America/Manaus', 'OFFSET' => -14400, 'ABBREVIATION' => 'AMT'),
		107 => array('NAME' => 'America/Montserrat', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		108 => array('NAME' => 'America/Rio_Branco', 'OFFSET' => -14400, 'ABBREVIATION' => 'AMT'),
		109 => array('NAME' => 'America/La_Paz', 'OFFSET' => -14400, 'ABBREVIATION' => 'BOT'),
		110 => array('NAME' => 'Atlantic/Bermuda', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		111 => array('NAME' => 'America/Antigua', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		112 => array('NAME' => 'America/Aruba', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		113 => array('NAME' => 'America/Dominica', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		114 => array('NAME' => 'America/Santo_Domingo', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		115 => array('NAME' => 'America/Eirunepe', 'OFFSET' => -14400, 'ABBREVIATION' => 'AMT'),
		116 => array('NAME' => 'America/Barbados', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		117 => array('NAME' => 'America/Blanc-Sablon', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		118 => array('NAME' => 'America/Boa_Vista', 'OFFSET' => -14400, 'ABBREVIATION' => 'AMT'),
		119 => array('NAME' => 'America/St_Barthelemy', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		120 => array('NAME' => 'America/Cuiaba', 'OFFSET' => -14400, 'ABBREVIATION' => 'AMT'),
		121 => array('NAME' => 'America/Curacao', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		122 => array('NAME' => 'America/Campo_Grande', 'OFFSET' => -14400, 'ABBREVIATION' => 'AMT'),
		123 => array('NAME' => 'America/Glace_Bay', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		124 => array('NAME' => 'America/Santiago', 'OFFSET' => -14400, 'ABBREVIATION' => 'CLST'),
		125 => array('NAME' => 'America/Grenada', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		126 => array('NAME' => 'America/Asuncion', 'OFFSET' => -14400, 'ABBREVIATION' => 'PYST'),
		127 => array('NAME' => 'America/St_Kitts', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		128 => array('NAME' => 'America/Goose_Bay', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		129 => array('NAME' => 'America/Halifax', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		130 => array('NAME' => 'America/Guyana', 'OFFSET' => -14400, 'ABBREVIATION' => 'GYT'),
		131 => array('NAME' => 'America/Guadeloupe', 'OFFSET' => -14400, 'ABBREVIATION' => 'AST'),
		132 => array('NAME' => 'America/St_Johns', 'OFFSET' => -12600, 'ABBREVIATION' => 'NST'),
		133 => array('NAME' => 'America/Santarem', 'OFFSET' => -10800, 'ABBREVIATION' => 'BRT'),
		134 => array('NAME' => 'America/Paramaribo', 'OFFSET' => -10800, 'ABBREVIATION' => 'SRT'),
		135 => array('NAME' => 'America/Miquelon', 'OFFSET' => -10800, 'ABBREVIATION' => 'PMST'),
		136 => array('NAME' => 'America/Sao_Paulo', 'OFFSET' => -10800, 'ABBREVIATION' => 'BRT'),
		137 => array('NAME' => 'America/Recife', 'OFFSET' => -10800, 'ABBREVIATION' => 'BRT'),
		138 => array('NAME' => 'America/Montevideo', 'OFFSET' => -10800, 'ABBREVIATION' => 'UYST'),
		139 => array('NAME' => 'America/Maceio', 'OFFSET' => -10800, 'ABBREVIATION' => 'BRT'),
		140 => array('NAME' => 'America/Araguaina', 'OFFSET' => -10800, 'ABBREVIATION' => 'BRT'),
		141 => array('NAME' => 'America/Argentina/Rio_Gallegos', 'OFFSET' => -10800, 'ABBREVIATION' => 'ART'),
		142 => array('NAME' => 'America/Argentina/Cordoba', 'OFFSET' => -10800, 'ABBREVIATION' => 'ART'),
		143 => array('NAME' => 'America/Argentina/Ushuaia', 'OFFSET' => -10800, 'ABBREVIATION' => 'ART'),
		144 => array('NAME' => 'America/Argentina/Tucuman', 'OFFSET' => -10800, 'ABBREVIATION' => 'ART'),
		145 => array('NAME' => 'America/Argentina/Catamarca', 'OFFSET' => -10800, 'ABBREVIATION' => 'ART'),
		146 => array('NAME' => 'America/Argentina/Buenos_Aires', 'OFFSET' => -10800, 'ABBREVIATION' => 'ART'),
		147 => array('NAME' => 'America/Argentina/San_Juan', 'OFFSET' => -10800, 'ABBREVIATION' => 'ART'),
		148 => array('NAME' => 'America/Bahia', 'OFFSET' => -10800, 'ABBREVIATION' => 'BRT'),
		149 => array('NAME' => 'America/Godthab', 'OFFSET' => -10800, 'ABBREVIATION' => 'WGT'),
		150 => array('NAME' => 'America/Argentina/Mendoza', 'OFFSET' => -10800, 'ABBREVIATION' => 'ART'),
		151 => array('NAME' => 'Antarctica/Rothera', 'OFFSET' => -10800, 'ABBREVIATION' => 'ROTT'),
		152 => array('NAME' => 'America/Cayenne', 'OFFSET' => -10800, 'ABBREVIATION' => 'GFT'),
		153 => array('NAME' => 'America/Argentina/La_Rioja', 'OFFSET' => -10800, 'ABBREVIATION' => 'ART'),
		154 => array('NAME' => 'America/Argentina/Jujuy', 'OFFSET' => -10800, 'ABBREVIATION' => 'ART'),
		155 => array('NAME' => 'America/Fortaleza', 'OFFSET' => -10800, 'ABBREVIATION' => 'BRT'),
		156 => array('NAME' => 'America/Belem', 'OFFSET' => -10800, 'ABBREVIATION' => 'BRT'),
		157 => array('NAME' => 'America/Argentina/Salta', 'OFFSET' => -10800, 'ABBREVIATION' => 'ART'),
		158 => array('NAME' => 'America/Noronha', 'OFFSET' => -7200, 'ABBREVIATION' => 'FNT'),
		159 => array('NAME' => 'Atlantic/South_Georgia', 'OFFSET' => -7200, 'ABBREVIATION' => 'GST'),
		160 => array('NAME' => 'America/Scoresbysund', 'OFFSET' => -3600, 'ABBREVIATION' => 'EGT'),
		161 => array('NAME' => 'Atlantic/Cape_Verde', 'OFFSET' => -3600, 'ABBREVIATION' => 'CVT'),
		162 => array('NAME' => 'Atlantic/Azores', 'OFFSET' => -3600, 'ABBREVIATION' => 'AZOT'),
		163 => array('NAME' => 'Africa/Bamako', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		164 => array('NAME' => 'Atlantic/Madeira', 'OFFSET' => 0, 'ABBREVIATION' => 'WET'),
		165 => array('NAME' => 'Africa/Conakry', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		166 => array('NAME' => 'Africa/Bissau', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		167 => array('NAME' => 'Africa/Abidjan', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		168 => array('NAME' => 'UTC', 'OFFSET' => 0, 'ABBREVIATION' => 'UTC'),
		169 => array('NAME' => 'Africa/Casablanca', 'OFFSET' => 0, 'ABBREVIATION' => 'WET'),
		170 => array('NAME' => 'Africa/Dakar', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		171 => array('NAME' => 'Africa/Banjul', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		172 => array('NAME' => 'Atlantic/Faroe', 'OFFSET' => 0, 'ABBREVIATION' => 'WET'),
		173 => array('NAME' => 'Africa/Freetown', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		174 => array('NAME' => 'Africa/El_Aaiun', 'OFFSET' => 0, 'ABBREVIATION' => 'WET'),
		175 => array('NAME' => 'Atlantic/Canary', 'OFFSET' => 0, 'ABBREVIATION' => 'WET'),
		176 => array('NAME' => 'Atlantic/Reykjavik', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		177 => array('NAME' => 'Europe/Jersey', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		178 => array('NAME' => 'Africa/Accra', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		179 => array('NAME' => 'Africa/Nouakchott', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		180 => array('NAME' => 'Europe/Guernsey', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		181 => array('NAME' => 'Africa/Ouagadougou', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		182 => array('NAME' => 'Africa/Monrovia', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		183 => array('NAME' => 'Atlantic/St_Helena', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		184 => array('NAME' => 'Africa/Sao_Tome', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		185 => array('NAME' => 'Europe/Lisbon', 'OFFSET' => 0, 'ABBREVIATION' => 'WET'),
		186 => array('NAME' => 'Europe/London', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		187 => array('NAME' => 'Europe/Dublin', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		188 => array('NAME' => 'Europe/Isle_of_Man', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		189 => array('NAME' => 'Africa/Lome', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		190 => array('NAME' => 'America/Danmarkshavn', 'OFFSET' => 0, 'ABBREVIATION' => 'GMT'),
		191 => array('NAME' => 'Europe/Gibraltar', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		192 => array('NAME' => 'Europe/Sarajevo', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		193 => array('NAME' => 'Europe/Rome', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		194 => array('NAME' => 'Europe/San_Marino', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		195 => array('NAME' => 'Europe/Vaduz', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		196 => array('NAME' => 'Europe/Warsaw', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		197 => array('NAME' => 'Europe/Zagreb', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		198 => array('NAME' => 'Europe/Zurich', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		199 => array('NAME' => 'Europe/Vienna', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		200 => array('NAME' => 'Europe/Vatican', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		201 => array('NAME' => 'Europe/Stockholm', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		202 => array('NAME' => 'Europe/Tirane', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		203 => array('NAME' => 'Europe/Prague', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		204 => array('NAME' => 'Europe/Skopje', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		205 => array('NAME' => 'Europe/Paris', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		206 => array('NAME' => 'Europe/Amsterdam', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		207 => array('NAME' => 'Europe/Andorra', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		208 => array('NAME' => 'Europe/Ljubljana', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		209 => array('NAME' => 'Europe/Luxembourg', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		210 => array('NAME' => 'Europe/Malta', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		211 => array('NAME' => 'Europe/Madrid', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		212 => array('NAME' => 'Europe/Belgrade', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		213 => array('NAME' => 'Europe/Berlin', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		214 => array('NAME' => 'Europe/Oslo', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		215 => array('NAME' => 'Europe/Copenhagen', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		216 => array('NAME' => 'Europe/Monaco', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		217 => array('NAME' => 'Europe/Budapest', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		218 => array('NAME' => 'Europe/Bratislava', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		219 => array('NAME' => 'Europe/Brussels', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		220 => array('NAME' => 'Europe/Podgorica', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		221 => array('NAME' => 'Africa/Brazzaville', 'OFFSET' => 3600, 'ABBREVIATION' => 'WAT'),
		222 => array('NAME' => 'Africa/Porto-Novo', 'OFFSET' => 3600, 'ABBREVIATION' => 'WAT'),
		223 => array('NAME' => 'Africa/Libreville', 'OFFSET' => 3600, 'ABBREVIATION' => 'WAT'),
		224 => array('NAME' => 'Africa/Tunis', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		225 => array('NAME' => 'Africa/Luanda', 'OFFSET' => 3600, 'ABBREVIATION' => 'WAT'),
		226 => array('NAME' => 'Africa/Kinshasa', 'OFFSET' => 3600, 'ABBREVIATION' => 'WAT'),
		227 => array('NAME' => 'Africa/Niamey', 'OFFSET' => 3600, 'ABBREVIATION' => 'WAT'),
		228 => array('NAME' => 'Africa/Ndjamena', 'OFFSET' => 3600, 'ABBREVIATION' => 'WAT'),
		229 => array('NAME' => 'Africa/Douala', 'OFFSET' => 3600, 'ABBREVIATION' => 'WAT'),
		230 => array('NAME' => 'Africa/Bangui', 'OFFSET' => 3600, 'ABBREVIATION' => 'WAT'),
		231 => array('NAME' => 'Africa/Windhoek', 'OFFSET' => 3600, 'ABBREVIATION' => 'WAST'),
		232 => array('NAME' => 'Africa/Lagos', 'OFFSET' => 3600, 'ABBREVIATION' => 'WAT'),
		233 => array('NAME' => 'Africa/Algiers', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		234 => array('NAME' => 'Africa/Malabo', 'OFFSET' => 3600, 'ABBREVIATION' => 'WAT'),
		235 => array('NAME' => 'Africa/Ceuta', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		236 => array('NAME' => 'Arctic/Longyearbyen', 'OFFSET' => 3600, 'ABBREVIATION' => 'CET'),
		237 => array('NAME' => 'Africa/Gaborone', 'OFFSET' => 7200, 'ABBREVIATION' => 'CAT'),
		238 => array('NAME' => 'Europe/Athens', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		239 => array('NAME' => 'Europe/Sofia', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		240 => array('NAME' => 'Europe/Tallinn', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		241 => array('NAME' => 'Africa/Bujumbura', 'OFFSET' => 7200, 'ABBREVIATION' => 'CAT'),
		242 => array('NAME' => 'Europe/Uzhgorod', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		243 => array('NAME' => 'Europe/Bucharest', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		244 => array('NAME' => 'Africa/Maputo', 'OFFSET' => 7200, 'ABBREVIATION' => 'CAT'),
		245 => array('NAME' => 'Europe/Istanbul', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		246 => array('NAME' => 'Africa/Cairo', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		247 => array('NAME' => 'Asia/Amman', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		248 => array('NAME' => 'Europe/Riga', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		249 => array('NAME' => 'Africa/Mbabane', 'OFFSET' => 7200, 'ABBREVIATION' => 'SAST'),
		250 => array('NAME' => 'Europe/Simferopol', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		251 => array('NAME' => 'Africa/Blantyre', 'OFFSET' => 7200, 'ABBREVIATION' => 'CAT'),
		252 => array('NAME' => 'Africa/Harare', 'OFFSET' => 7200, 'ABBREVIATION' => 'CAT'),
		253 => array('NAME' => 'Europe/Vilnius', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		254 => array('NAME' => 'Africa/Lusaka', 'OFFSET' => 7200, 'ABBREVIATION' => 'CAT'),
		255 => array('NAME' => 'Africa/Lubumbashi', 'OFFSET' => 7200, 'ABBREVIATION' => 'CAT'),
		256 => array('NAME' => 'Asia/Jerusalem', 'OFFSET' => 7200, 'ABBREVIATION' => 'IST'),
		257 => array('NAME' => 'Africa/Tripoli', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		258 => array('NAME' => 'Europe/Kiev', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		259 => array('NAME' => 'Asia/Gaza', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		260 => array('NAME' => 'Asia/Damascus', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		261 => array('NAME' => 'Europe/Kaliningrad', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		262 => array('NAME' => 'Europe/Helsinki', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		263 => array('NAME' => 'Africa/Johannesburg', 'OFFSET' => 7200, 'ABBREVIATION' => 'SAST'),
		264 => array('NAME' => 'Europe/Chisinau', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		265 => array('NAME' => 'Africa/Kigali', 'OFFSET' => 7200, 'ABBREVIATION' => 'CAT'),
		266 => array('NAME' => 'Africa/Maseru', 'OFFSET' => 7200, 'ABBREVIATION' => 'SAST'),
		267 => array('NAME' => 'Asia/Nicosia', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		268 => array('NAME' => 'Europe/Mariehamn', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		269 => array('NAME' => 'Asia/Beirut', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		270 => array('NAME' => 'Europe/Minsk', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		271 => array('NAME' => 'Europe/Zaporozhye', 'OFFSET' => 7200, 'ABBREVIATION' => 'EET'),
		272 => array('NAME' => 'Africa/Djibouti', 'OFFSET' => 10800, 'ABBREVIATION' => 'EAT'),
		273 => array('NAME' => 'Europe/Moscow', 'OFFSET' => 10800, 'ABBREVIATION' => 'MSK'),
		274 => array('NAME' => 'Africa/Khartoum', 'OFFSET' => 10800, 'ABBREVIATION' => 'EAT'),
		275 => array('NAME' => 'Africa/Dar_es_Salaam', 'OFFSET' => 10800, 'ABBREVIATION' => 'EAT'),
		276 => array('NAME' => 'Africa/Kampala', 'OFFSET' => 10800, 'ABBREVIATION' => 'EAT'),
		277 => array('NAME' => 'Africa/Mogadishu', 'OFFSET' => 10800, 'ABBREVIATION' => 'EAT'),
		278 => array('NAME' => 'Asia/Kuwait', 'OFFSET' => 10800, 'ABBREVIATION' => 'AST'),
		279 => array('NAME' => 'Europe/Volgograd', 'OFFSET' => 10800, 'ABBREVIATION' => 'VOLT'),
		280 => array('NAME' => 'Antarctica/Syowa', 'OFFSET' => 10800, 'ABBREVIATION' => 'SYOT'),
		281 => array('NAME' => 'Africa/Asmara', 'OFFSET' => 10800, 'ABBREVIATION' => 'EAT'),
		282 => array('NAME' => 'Indian/Antananarivo', 'OFFSET' => 10800, 'ABBREVIATION' => 'EAT'),
		283 => array('NAME' => 'Indian/Comoro', 'OFFSET' => 10800, 'ABBREVIATION' => 'EAT'),
		284 => array('NAME' => 'Indian/Mayotte', 'OFFSET' => 10800, 'ABBREVIATION' => 'EAT'),
		285 => array('NAME' => 'Asia/Bahrain', 'OFFSET' => 10800, 'ABBREVIATION' => 'AST'),
		286 => array('NAME' => 'Asia/Baghdad', 'OFFSET' => 10800, 'ABBREVIATION' => 'AST'),
		287 => array('NAME' => 'Asia/Aden', 'OFFSET' => 10800, 'ABBREVIATION' => 'AST'),
		288 => array('NAME' => 'Africa/Addis_Ababa', 'OFFSET' => 10800, 'ABBREVIATION' => 'EAT'),
		289 => array('NAME' => 'Europe/Samara', 'OFFSET' => 10800, 'ABBREVIATION' => 'SAMT'),
		290 => array('NAME' => 'Asia/Riyadh', 'OFFSET' => 10800, 'ABBREVIATION' => 'AST'),
		291 => array('NAME' => 'Africa/Nairobi', 'OFFSET' => 10800, 'ABBREVIATION' => 'EAT'),
		292 => array('NAME' => 'Asia/Qatar', 'OFFSET' => 10800, 'ABBREVIATION' => 'AST'),
		293 => array('NAME' => 'Asia/Tehran', 'OFFSET' => 12600, 'ABBREVIATION' => 'IRST'),
		294 => array('NAME' => 'Indian/Reunion', 'OFFSET' => 14400, 'ABBREVIATION' => 'RET'),
		295 => array('NAME' => 'Indian/Mauritius', 'OFFSET' => 14400, 'ABBREVIATION' => 'MUT'),
		296 => array('NAME' => 'Asia/Dubai', 'OFFSET' => 14400, 'ABBREVIATION' => 'GST'),
		297 => array('NAME' => 'Asia/Baku', 'OFFSET' => 14400, 'ABBREVIATION' => 'AZT'),
		298 => array('NAME' => 'Asia/Tbilisi', 'OFFSET' => 14400, 'ABBREVIATION' => 'GET'),
		299 => array('NAME' => 'Asia/Yerevan', 'OFFSET' => 14400, 'ABBREVIATION' => 'AMT'),
		300 => array('NAME' => 'Asia/Muscat', 'OFFSET' => 14400, 'ABBREVIATION' => 'GST'),
		301 => array('NAME' => 'Indian/Mahe', 'OFFSET' => 14400, 'ABBREVIATION' => 'SCT'),
		302 => array('NAME' => 'Asia/Kabul', 'OFFSET' => 16200, 'ABBREVIATION' => 'AFT'),
		303 => array('NAME' => 'Asia/Tashkent', 'OFFSET' => 18000, 'ABBREVIATION' => 'UZT'),
		304 => array('NAME' => 'Asia/Karachi', 'OFFSET' => 18000, 'ABBREVIATION' => 'PKT'),
		305 => array('NAME' => 'Asia/Yekaterinburg', 'OFFSET' => 18000, 'ABBREVIATION' => 'YEKT'),
		306 => array('NAME' => 'Indian/Kerguelen', 'OFFSET' => 18000, 'ABBREVIATION' => 'TFT'),
		307 => array('NAME' => 'Indian/Maldives', 'OFFSET' => 18000, 'ABBREVIATION' => 'MVT'),
		308 => array('NAME' => 'Asia/Dushanbe', 'OFFSET' => 18000, 'ABBREVIATION' => 'TJT'),
		309 => array('NAME' => 'Asia/Ashgabat', 'OFFSET' => 18000, 'ABBREVIATION' => 'TMT'),
		310 => array('NAME' => 'Asia/Oral', 'OFFSET' => 18000, 'ABBREVIATION' => 'ORAT'),
		311 => array('NAME' => 'Asia/Samarkand', 'OFFSET' => 18000, 'ABBREVIATION' => 'UZT'),
		312 => array('NAME' => 'Antarctica/Mawson', 'OFFSET' => 18000, 'ABBREVIATION' => 'MAWT'),
		313 => array('NAME' => 'Asia/Aqtobe', 'OFFSET' => 18000, 'ABBREVIATION' => 'AQTT'),
		314 => array('NAME' => 'Asia/Aqtau', 'OFFSET' => 18000, 'ABBREVIATION' => 'AQTT'),
		315 => array('NAME' => 'Asia/Kolkata', 'OFFSET' => 19800, 'ABBREVIATION' => 'IST'),
		316 => array('NAME' => 'Asia/Colombo', 'OFFSET' => 19800, 'ABBREVIATION' => 'IST'),
		317 => array('NAME' => 'Asia/Kathmandu', 'OFFSET' => 20700, 'ABBREVIATION' => 'NPT'),
		318 => array('NAME' => 'Indian/Chagos', 'OFFSET' => 21600, 'ABBREVIATION' => 'IOT'),
		319 => array('NAME' => 'Antarctica/Vostok', 'OFFSET' => 21600, 'ABBREVIATION' => 'VOST'),
		320 => array('NAME' => 'Asia/Omsk', 'OFFSET' => 21600, 'ABBREVIATION' => 'OMST'),
		321 => array('NAME' => 'Asia/Novosibirsk', 'OFFSET' => 21600, 'ABBREVIATION' => 'NOVT'),
		322 => array('NAME' => 'Asia/Thimphu', 'OFFSET' => 21600, 'ABBREVIATION' => 'BTT'),
		323 => array('NAME' => 'Asia/Dhaka', 'OFFSET' => 21600, 'ABBREVIATION' => 'BDT'),
		324 => array('NAME' => 'Asia/Bishkek', 'OFFSET' => 21600, 'ABBREVIATION' => 'KGT'),
		325 => array('NAME' => 'Asia/Almaty', 'OFFSET' => 21600, 'ABBREVIATION' => 'ALMT'),
		326 => array('NAME' => 'Asia/Qyzylorda', 'OFFSET' => 21600, 'ABBREVIATION' => 'QYZT'),
		327 => array('NAME' => 'Asia/Novokuznetsk', 'OFFSET' => 21600, 'ABBREVIATION' => 'NOVT'),
		328 => array('NAME' => 'Asia/Rangoon', 'OFFSET' => 23400, 'ABBREVIATION' => 'MMT'),
		329 => array('NAME' => 'Indian/Cocos', 'OFFSET' => 23400, 'ABBREVIATION' => 'CCT'),
		330 => array('NAME' => 'Asia/Pontianak', 'OFFSET' => 25200, 'ABBREVIATION' => 'WIT'),
		331 => array('NAME' => 'Asia/Bangkok', 'OFFSET' => 25200, 'ABBREVIATION' => 'ICT'),
		332 => array('NAME' => 'Antarctica/Davis', 'OFFSET' => 25200, 'ABBREVIATION' => 'DAVT'),
		333 => array('NAME' => 'Asia/Phnom_Penh', 'OFFSET' => 25200, 'ABBREVIATION' => 'ICT'),
		334 => array('NAME' => 'Asia/Ho_Chi_Minh', 'OFFSET' => 25200, 'ABBREVIATION' => 'ICT'),
		335 => array('NAME' => 'Indian/Christmas', 'OFFSET' => 25200, 'ABBREVIATION' => 'CXT'),
		336 => array('NAME' => 'Asia/Hovd', 'OFFSET' => 25200, 'ABBREVIATION' => 'HOVT'),
		337 => array('NAME' => 'Asia/Krasnoyarsk', 'OFFSET' => 25200, 'ABBREVIATION' => 'KRAT'),
		338 => array('NAME' => 'Asia/Jakarta', 'OFFSET' => 25200, 'ABBREVIATION' => 'WIT'),
		339 => array('NAME' => 'Asia/Vientiane', 'OFFSET' => 25200, 'ABBREVIATION' => 'ICT'),
		340 => array('NAME' => 'Asia/Chongqing', 'OFFSET' => 28800, 'ABBREVIATION' => 'CST'),
		341 => array('NAME' => 'Asia/Kuching', 'OFFSET' => 28800, 'ABBREVIATION' => 'MYT'),
		342 => array('NAME' => 'Asia/Macau', 'OFFSET' => 28800, 'ABBREVIATION' => 'CST'),
		343 => array('NAME' => 'Asia/Makassar', 'OFFSET' => 28800, 'ABBREVIATION' => 'CIT'),
		344 => array('NAME' => 'Asia/Kashgar', 'OFFSET' => 28800, 'ABBREVIATION' => 'CST'),
		345 => array('NAME' => 'Asia/Irkutsk', 'OFFSET' => 28800, 'ABBREVIATION' => 'IRKT'),
		346 => array('NAME' => 'Asia/Brunei', 'OFFSET' => 28800, 'ABBREVIATION' => 'BNT'),
		347 => array('NAME' => 'Asia/Choibalsan', 'OFFSET' => 28800, 'ABBREVIATION' => 'CHOT'),
		348 => array('NAME' => 'Asia/Taipei', 'OFFSET' => 28800, 'ABBREVIATION' => 'CST'),
		349 => array('NAME' => 'Asia/Harbin', 'OFFSET' => 28800, 'ABBREVIATION' => 'CST'),
		350 => array('NAME' => 'Asia/Hong_Kong', 'OFFSET' => 28800, 'ABBREVIATION' => 'HKT'),
		351 => array('NAME' => 'Asia/Manila', 'OFFSET' => 28800, 'ABBREVIATION' => 'PHT'),
		352 => array('NAME' => 'Asia/Kuala_Lumpur', 'OFFSET' => 28800, 'ABBREVIATION' => 'MYT'),
		353 => array('NAME' => 'Asia/Shanghai', 'OFFSET' => 28800, 'ABBREVIATION' => 'CST'),
		354 => array('NAME' => 'Antarctica/Casey', 'OFFSET' => 28800, 'ABBREVIATION' => 'WST'),
		355 => array('NAME' => 'Asia/Ulaanbaatar', 'OFFSET' => 28800, 'ABBREVIATION' => 'ULAT'),
		356 => array('NAME' => 'Asia/Urumqi', 'OFFSET' => 28800, 'ABBREVIATION' => 'CST'),
		357 => array('NAME' => 'Asia/Singapore', 'OFFSET' => 28800, 'ABBREVIATION' => 'SGT'),
		358 => array('NAME' => 'Australia/Perth', 'OFFSET' => 28800, 'ABBREVIATION' => 'WST'),
		359 => array('NAME' => 'Australia/Eucla', 'OFFSET' => 31500, 'ABBREVIATION' => 'CWST'),
		360 => array('NAME' => 'Asia/Tokyo', 'OFFSET' => 32400, 'ABBREVIATION' => 'JST'),
		361 => array('NAME' => 'Asia/Dili', 'OFFSET' => 32400, 'ABBREVIATION' => 'TLT'),
		362 => array('NAME' => 'Asia/Seoul', 'OFFSET' => 32400, 'ABBREVIATION' => 'KST'),
		363 => array('NAME' => 'Pacific/Palau', 'OFFSET' => 32400, 'ABBREVIATION' => 'PWT'),
		364 => array('NAME' => 'Asia/Yakutsk', 'OFFSET' => 32400, 'ABBREVIATION' => 'YAKT'),
		365 => array('NAME' => 'Asia/Pyongyang', 'OFFSET' => 32400, 'ABBREVIATION' => 'KST'),
		366 => array('NAME' => 'Asia/Jayapura', 'OFFSET' => 32400, 'ABBREVIATION' => 'EIT'),
		367 => array('NAME' => 'Australia/Broken_Hill', 'OFFSET' => 34200, 'ABBREVIATION' => 'CST'),
		368 => array('NAME' => 'Australia/Darwin', 'OFFSET' => 34200, 'ABBREVIATION' => 'CST'),
		369 => array('NAME' => 'Australia/Adelaide', 'OFFSET' => 34200, 'ABBREVIATION' => 'CST'),
		370 => array('NAME' => 'Australia/Lindeman', 'OFFSET' => 36000, 'ABBREVIATION' => 'EST'),
		371 => array('NAME' => 'Pacific/Guam', 'OFFSET' => 36000, 'ABBREVIATION' => 'ChST'),
		372 => array('NAME' => 'Australia/Melbourne', 'OFFSET' => 36000, 'ABBREVIATION' => 'EST'),
		373 => array('NAME' => 'Pacific/Saipan', 'OFFSET' => 36000, 'ABBREVIATION' => 'ChST'),
		374 => array('NAME' => 'Antarctica/DumontDUrville', 'OFFSET' => 36000, 'ABBREVIATION' => 'DDUT'),
		375 => array('NAME' => 'Pacific/Port_Moresby', 'OFFSET' => 36000, 'ABBREVIATION' => 'PGT'),
		376 => array('NAME' => 'Australia/Lord_Howe', 'OFFSET' => 36000, 'ABBREVIATION' => 'LHST'),
		377 => array('NAME' => 'Pacific/Chuuk', 'OFFSET' => 36000, 'ABBREVIATION' => 'CHUT'),
		378 => array('NAME' => 'Australia/Sydney', 'OFFSET' => 36000, 'ABBREVIATION' => 'EST'),
		379 => array('NAME' => 'Asia/Vladivostok', 'OFFSET' => 36000, 'ABBREVIATION' => 'VLAT'),
		380 => array('NAME' => 'Australia/Currie', 'OFFSET' => 36000, 'ABBREVIATION' => 'EST'),
		381 => array('NAME' => 'Australia/Brisbane', 'OFFSET' => 36000, 'ABBREVIATION' => 'EST'),
		382 => array('NAME' => 'Australia/Hobart', 'OFFSET' => 36000, 'ABBREVIATION' => 'EST'),
		383 => array('NAME' => 'Asia/Sakhalin', 'OFFSET' => 36000, 'ABBREVIATION' => 'SAKT'),
		384 => array('NAME' => 'Asia/Anadyr', 'OFFSET' => 39600, 'ABBREVIATION' => 'ANAT'),
		385 => array('NAME' => 'Antarctica/Macquarie', 'OFFSET' => 39600, 'ABBREVIATION' => 'MIST'),
		386 => array('NAME' => 'Pacific/Noumea', 'OFFSET' => 39600, 'ABBREVIATION' => 'NCT'),
		387 => array('NAME' => 'Asia/Kamchatka', 'OFFSET' => 39600, 'ABBREVIATION' => 'PETT'),
		388 => array('NAME' => 'Pacific/Pohnpei', 'OFFSET' => 39600, 'ABBREVIATION' => 'PONT'),
		389 => array('NAME' => 'Pacific/Kosrae', 'OFFSET' => 39600, 'ABBREVIATION' => 'KOST'),
		390 => array('NAME' => 'Pacific/Efate', 'OFFSET' => 39600, 'ABBREVIATION' => 'VUT'),
		391 => array('NAME' => 'Asia/Magadan', 'OFFSET' => 39600, 'ABBREVIATION' => 'MAGT'),
		392 => array('NAME' => 'Pacific/Guadalcanal', 'OFFSET' => 39600, 'ABBREVIATION' => 'SBT'),
		393 => array('NAME' => 'Pacific/Norfolk', 'OFFSET' => 41400, 'ABBREVIATION' => 'NFT'),
		394 => array('NAME' => 'Pacific/Wallis', 'OFFSET' => 43200, 'ABBREVIATION' => 'WFT'),
		395 => array('NAME' => 'Pacific/Tarawa', 'OFFSET' => 43200, 'ABBREVIATION' => 'GILT'),
		396 => array('NAME' => 'Pacific/Wake', 'OFFSET' => 43200, 'ABBREVIATION' => 'WAKT'),
		397 => array('NAME' => 'Antarctica/South_Pole', 'OFFSET' => 43200, 'ABBREVIATION' => 'NZDT'),
		398 => array('NAME' => 'Antarctica/McMurdo', 'OFFSET' => 43200, 'ABBREVIATION' => 'NZDT'),
		399 => array('NAME' => 'Pacific/Auckland', 'OFFSET' => 43200, 'ABBREVIATION' => 'NZDT'),
		400 => array('NAME' => 'Pacific/Funafuti', 'OFFSET' => 43200, 'ABBREVIATION' => 'TVT'),
		401 => array('NAME' => 'Pacific/Kwajalein', 'OFFSET' => 43200, 'ABBREVIATION' => 'MHT'),
		402 => array('NAME' => 'Pacific/Majuro', 'OFFSET' => 43200, 'ABBREVIATION' => 'MHT'),
		403 => array('NAME' => 'Pacific/Fiji', 'OFFSET' => 43200, 'ABBREVIATION' => 'FJT'),
		404 => array('NAME' => 'Pacific/Nauru', 'OFFSET' => 43200, 'ABBREVIATION' => 'NRT'),
		405 => array('NAME' => 'Pacific/Chatham', 'OFFSET' => 45900, 'ABBREVIATION' => 'CHADT'),
		406 => array('NAME' => 'Pacific/Enderbury', 'OFFSET' => 46800, 'ABBREVIATION' => 'PHOT'),
		407 => array('NAME' => 'Pacific/Tongatapu', 'OFFSET' => 46800, 'ABBREVIATION' => 'TOT'),
		408 => array('NAME' => 'Pacific/Kiritimati', 'OFFSET' => 50400, 'ABBREVIATION' => 'LINT')
	);

	public static function SetIDInside($FilteredTimeZones) {
		foreach ($FilteredTimeZones as $ID => $Val) {
			$Val['ID'] = $ID;
			$FilteredTimeZones[$ID] = $Val;
		}
		return $FilteredTimeZones;
	}

	public static function Get_ByID($ID, $Field = NULL) {
		if (@self::$arrTimeZones[$ID])
			self::$arrTimeZones[$ID]['ID'] = $ID;
		return $Field ? @self::$arrTimeZones[$ID][$Field] : @self::$arrTimeZones[$ID];
	}

	public static function Get_ByName($Name, $Field = NULL) {
		$result = self::SetIDInside(
						array_filter(self::$arrTimeZones, create_function('$val', "return stripos(\$val['NAME'], '$Name')!==false;"))
		);
		$result = array_shift($result);
		return $Field ? @$result[$Field] : $result;
	}

	public static function Get_ByOffset($Offset) { //, $Field = NULL
		return self::SetIDInside(
						array_filter(self::$arrTimeZones, create_function('$val', "return \$val['OFFSET']==$Offset;"))
		);
//		return $Field ? @$result[$Field] : $result;
	}

}

?>